name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonar_scan:
    runs-on: xyz

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use .NET 8
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          overwrite-settings: false

      - name: Install SonarCloud scanner
        run: |
          mkdir -p .sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
          dotnet tool install --global dotnet-sonarscanner
          chmod +x ./.sonar/scanner/dotnet-sonarscanner
      - name: Install dotnet-coverage globally
        run: | 
          dotnet tool install -g dotnet-coverage
      - name: Sonar Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"xyz" /o:"tyz" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="./coverage.opencover"
          dotnet buildx.sln --no-incremental
          x.sln --no-build --logger "trx;LogFileName=test-results.trx"
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
